"""
DEMO: A neural net controls a real Linux VM through direct signals.

Zero tokens generated by the LLM. The backbone understands, the action
head classifies the syscall + args, and the buffer head produces the
exact file content — all in a single forward pass.

Usage:
    uv run demo              # run preset scenarios
    uv run demo --interactive  # type your own instructions
"""

import os
import sys
import time
import json

import mlx.core as mx
import numpy as np

from .kernel import VM, STATE_DIM
from .model import (
    ReflexHead, SYSCALL_TABLE, ARG_DIM,
    CONTEXT_LEN, load_backbone,
    encode_instruction_last,
    encode_prev_action, decode_syscall, set_arg_vocab, get_arg_vocab,
)

DIR = os.path.dirname(os.path.abspath(__file__))

B = "\033[1m"
D = "\033[2m"
G = "\033[32m"
Y = "\033[33m"
R = "\033[31m"
N = "\033[0m"

# Instructions the model knows (must match train.py)
KNOWN_INSTRUCTIONS = {
    "create hello.py with hello world": ("python3 hello.py", 3),
    "create main.py with a loop": ("python3 main.py", 3),
    "create app.py with pid": ("python3 app.py", 3),
    "create config.json": ("cat config.json", 3),
    "create README.md": ("cat README.md", 3),
    "create test.py with assertions": ("python3 test.py", 3),
    "create data.csv": ("cat data.csv", 3),
    "create setup.sh": ("cat setup.sh", 3),
    "create sales.csv with sales data": ("cat sales.csv", 3),
    "create analyze.py to analyze csv": ("cat analyze.py", 3),
    "create directory src": (None, 1),
    "create directory lib": (None, 1),
    "create directory tests": (None, 1),
    "create directory myapp": (None, 1),
    "create directory pkg": (None, 1),
    "create src/main.py": ("python3 src/main.py", 3),
    "create lib/utils.py": ("cat lib/utils.py", 3),
    "delete hello.py": (None, 1),
    "delete main.py": (None, 1),
    "delete config.json": (None, 1),
    "delete data.csv": (None, 1),
}

SCENARIOS = [
    {
        "title": "Create a Python hello world and run it",
        "steps": [("create hello.py with hello world", 3)],
        "verify": "python3 hello.py",
    },
    {
        "title": "Analyze sales data from CSV",
        "steps": [
            ("create sales.csv with sales data", 3),
            ("create analyze.py to analyze csv", 3),
        ],
        "verify": "python3 analyze.py",
    },
    {
        "title": "Create and run a test suite",
        "steps": [("create test.py with assertions", 3)],
        "verify": "python3 test.py",
    },
    {
        "title": "Create a loop program and run it",
        "steps": [("create main.py with a loop", 3)],
        "verify": "python3 main.py",
    },
]


def execute_instruction(instr, n_steps, head, backbone, tokenizer, vm, prev_syscall_idx=-1, prev_arg_values=None):
    """Execute one instruction for n_steps syscalls. Returns timing info."""
    if prev_arg_values is None:
        prev_arg_values = np.zeros(ARG_DIM, dtype=np.float32)

    state_history = []
    instr_emb = encode_instruction_last(instr, backbone, tokenizer)
    mx.eval(instr_emb)

    total_us = 0

    for step in range(n_steps):
        state = vm.observe()

        window = np.zeros((CONTEXT_LEN, STATE_DIM), dtype=np.float32)
        hist = state_history + [state]
        for i, s in enumerate(hist[-CONTEXT_LEN:]):
            window[CONTEXT_LEN - len(hist[-CONTEXT_LEN:]) + i] = s

        prev = encode_prev_action(prev_syscall_idx, prev_arg_values)

        t0 = time.perf_counter()
        syscall_logits, arg_logits, buf_logits = head(
            instr_emb, mx.array(window[None]), mx.array(prev[None]),
        )
        mx.eval(syscall_logits, arg_logits, buf_logits)
        us = (time.perf_counter() - t0) * 1e6
        total_us += us

        pred_idx = int(mx.argmax(syscall_logits[0]).item())
        arg_indices = np.array(mx.argmax(arg_logits[0], axis=1))
        buf_bytes = np.array(mx.argmax(buf_logits[0], axis=1)).astype(np.uint8)
        syscall_name = SYSCALL_TABLE[pred_idx]

        confidence = float(mx.softmax(syscall_logits[0])[pred_idx].item())
        buf_preview = ''.join(chr(b) if 32 <= b < 127 else '.' for b in buf_bytes[:16])

        print(f"  {D}step {step}{N} → {Y}{syscall_name:10s}{N} "
              f"{D}conf={confidence:.2f}  buf=[{buf_preview}]  ({us:.0f}µs){N}")

        raw = decode_syscall(pred_idx, arg_indices, buf_bytes)
        ret, err = vm.execute(raw)
        if ret < 0:
            print(f"    {R}ret={ret} err={err}{N}")

        prev_syscall_idx = pred_idx
        prev_arg_values = arg_indices.astype(np.float32)
        state_history.append(state)

    return total_us, n_steps


def run_scenarios(head, backbone, tokenizer, vm):
    """Run preset scenarios."""
    grand_total_us = 0
    grand_total_ops = 0

    for scenario in SCENARIOS:
        print(f"\n  {B}{scenario['title']}{N}")
        print(f"  {'─' * 50}")

        vm.run_command("rm -rf /workspace/* 2>/dev/null")

        for instr, n_steps in scenario["steps"]:
            us, ops = execute_instruction(instr, n_steps, head, backbone, tokenizer, vm)
            grand_total_us += us
            grand_total_ops += ops

        if scenario.get("verify"):
            code, stdout = vm.run_command(scenario["verify"])
            if stdout.strip():
                print(f"\n  {G}$ {scenario['verify']}{N}")
                for line in stdout.strip().split("\n"):
                    print(f"  {G}  {line}{N}")

    return grand_total_us, grand_total_ops


def run_interactive(head, backbone, tokenizer, vm):
    """Interactive mode: user types instructions."""
    print(f"\n  {B}Known instructions:{N}")
    for instr in sorted(KNOWN_INSTRUCTIONS):
        print(f"    {D}{instr}{N}")

    print(f"\n  {D}Type an instruction, 'ls' to list files, 'reset' to clear, 'quit' to exit.{N}")
    print(f"  {D}After file creation, the file is automatically shown/run.{N}\n")

    grand_total_us = 0
    grand_total_ops = 0

    while True:
        try:
            raw_input = input(f"  {B}>{N} ").strip()
        except (EOFError, KeyboardInterrupt):
            break

        if not raw_input:
            continue
        if raw_input == "quit":
            break
        if raw_input == "ls":
            _, out = vm.run_command("ls -la /workspace/")
            print(f"  {D}{out.strip()}{N}")
            continue
        if raw_input == "reset":
            vm.run_command("rm -rf /workspace/* 2>/dev/null")
            print(f"  {D}Workspace cleared.{N}")
            continue

        instr = raw_input
        if instr in KNOWN_INSTRUCTIONS:
            verify_cmd, n_steps = KNOWN_INSTRUCTIONS[instr]
        else:
            # Try it anyway — the backbone will encode it, results may vary
            print(f"  {D}(unknown instruction — trying anyway, 3 steps){N}")
            verify_cmd = None
            n_steps = 3

        us, ops = execute_instruction(instr, n_steps, head, backbone, tokenizer, vm)
        grand_total_us += us
        grand_total_ops += ops

        if verify_cmd:
            code, stdout = vm.run_command(verify_cmd)
            if stdout.strip():
                print(f"  {G}$ {verify_cmd}{N}")
                for line in stdout.strip().split("\n"):
                    print(f"  {G}  {line}{N}")
        print()

    return grand_total_us, grand_total_ops


def print_summary(total_us, total_ops):
    if total_ops == 0:
        return
    avg_us = total_us / total_ops
    print(f"\n{B}{'═' * 62}{N}")
    print(f"{B}  RESULTS{N}")
    print(f"{B}{'═' * 62}{N}")
    print(f"\n  Syscalls executed:      {total_ops}")
    print(f"  Total action time:      {total_us/1000:.1f} ms")
    print(f"  Avg per syscall:        {avg_us:.0f} µs")
    print(f"  LLM tokens generated:   {B}0{N}")

    est_text_ms = total_ops * 30 * 15
    speedup = est_text_ms * 1000 / total_us
    print(f"\n  {D}Same backbone generating text (estimated):{N}")
    print(f"  {D}  {total_ops * 30} tokens × 15ms/tok = {est_text_ms}ms{N}")
    print(f"\n  {B}{G}Action head speedup: {speedup:.0f}x vs text generation{N}")


def main():
    weights_path = os.path.join(DIR, "head_weights.npz")
    vocab_path = os.path.join(DIR, "arg_vocab.json")
    if not os.path.exists(weights_path):
        print(f"{R}No trained weights found. Run: uv run train{N}")
        return

    interactive = "--interactive" in sys.argv or "-i" in sys.argv

    print(f"""
{B}╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║   Reflex: LLM understands, action head controls               ║
║                                                               ║
║   Backbone: Qwen2.5-Coder-1.5B (frozen, zero tokens output)  ║
║   Action head: understanding → raw syscall signals             ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝{N}
""")

    print(f"{D}Loading backbone...{N}")
    backbone, tokenizer = load_backbone()

    print(f"{D}Loading action head...{N}")
    with open(vocab_path) as f:
        set_arg_vocab(json.load(f))
    head = ReflexHead(n_arg_vocab=len(get_arg_vocab()))
    head.load_weights(list(mx.load(weights_path).items()))

    print(f"\n{D}Booting Linux VM...{N}")
    vm = VM(build=False)

    print(f"\n{B}{'═' * 62}{N}")
    print(f"{B}  LIVE: understanding → signals → Linux kernel{N}")
    print(f"{B}{'═' * 62}{N}")

    if interactive:
        total_us, total_ops = run_interactive(head, backbone, tokenizer, vm)
    else:
        total_us, total_ops = run_scenarios(head, backbone, tokenizer, vm)

    print_summary(total_us, total_ops)

    vm.stop()
    print(f"\n{D}VM stopped.{N}")


if __name__ == "__main__":
    main()
